target: cpu-cluster
framework: Python
communicator: None
nodeCount: 1
environment:
  environmentVariables:
    EXAMPLE_ENV_VAR: EXAMPLE_VALUE
  python:
    userManagedDependencies: true
    interpreterPath: python
    condaDependenciesFile: ./train-conda.yml
  docker:
    enabled: true
    baseImage: amldemoimages.azurecr.io/base-r-image:latest
    arguments: []
mpi:
    processCountPerNode: 1